line-length = 79
src = ["src"]

[lint]
select = [
    "E",
    "F",
    "BLE",
    "B",
    "COM",
    "C4",
    "ERA",
    "T20",
    "I",
    "N",
    "ASYNC",
    "PIE",
    "RUF",
]

ignore = [
    "RUF001",
]

[lint.isort]
no-lines-before = ["local-folder"]

[lint.flake8-tidy-imports]
ban-relative-imports = "parents"